# Generated by Django 4.1 on 2022-08-28 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios',
            name='idPost',
        ),
        migrations.RemoveField(
            model_name='comentarios',
            name='idUsuarios',
        ),
    ]
