# Generated by Django 4.1 on 2022-08-17 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=255)),
                ('comentario', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('fecha', models.TimeField()),
                ('idPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
                ('idUsuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios')),
            ],
        ),
    ]
