# Generated by Django 4.1 on 2022-08-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('detalles', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=255)),
                ('fecha', models.TimeField()),
            ],
        ),
    ]
